In [20]:
import pandas as pd
from io import StringIO

In [21]:
data = "nconst\tprimaryName\tbirthYear\tdeathYear\tprimaryProfession\tknownForTitles\timg_url_asset\nnm0000019\tFederico Fellini\t1920\t1993\twriter,director,actor\ttt0071129,tt0047528,tt0050783,tt0056801\thttps://image.tmdb.org/t/p/{width_variable}/jH2VnHAuI0UbTWsnrjMPro0fC9j.jpg"

In [22]:
data_file = StringIO(data)

In [23]:
data = pd.read_csv(data_file, sep='\t')

In [25]:
uploaded_file = "poop"

In [27]:
{"error":f"Something went wrong with file {uploaded_file}"}

{'error': 'Something went wrong with file poop'}

In [2]:
titles = pd.read_csv("../truncated_data/truncated_title.basics.tsv", sep='\t')

In [3]:
akas = pd.read_csv("../truncated_data/truncated_title.akas.tsv", sep='\t')

In [4]:
crew = pd.read_csv("../truncated_data/truncated_title.crew.tsv", sep='\t')

In [5]:
names = pd.read_csv("../truncated_data/truncated_name.basics.tsv", sep='\t')

In [6]:
episodes = pd.read_csv("../truncated_data/truncated_title.episode.tsv", sep='\t')

In [7]:
principals = pd.read_csv("../truncated_data/truncated_title.principals.tsv", sep='\t')

In [8]:
ratings = pd.read_csv("../truncated_data/truncated_title.ratings.tsv", sep='\t')

In [14]:
episodes

        tconst parentTconst seasonNumber episodeNumber
0    tt0073481    tt0298685            1             4
1    tt0088283    tt0806901           20             8
2    tt0088656    tt0088655            1             2
3    tt0088657    tt0088655            1             3
4    tt0090780    tt0190210            1             3
..         ...          ...          ...           ...
145  tt0103054    tt0806910            1           240
146  tt0103062    tt0297625            3             2
147  tt0103071    tt0806901           21             9
148  tt0103145    tt0985040            9             2
149  tt0103149    tt0806910            1           243

[150 rows x 4 columns]

In [12]:
titles[titles['tconst']=='tt0073481']

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
350,tt0073481,tvEpisode,Old Times,Old Times,0,1991,\N,78,Drama

In [59]:
ratings

        tconst  averageRating  numVotes
0    tt0000929            5.3        46
1    tt0015414            5.2        16
2    tt0015724            6.1        26
3    tt0034841            6.3       282
4    tt0038086            7.0        27
..         ...            ...       ...
437  tt0103054            5.2        50
438  tt0103062            8.2        41
439  tt0103071            6.6        56
440  tt0103145            7.6        12
441  tt0103149            6.4        51

[442 rows x 3 columns]

In [60]:
akas

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000929,1,Willys Streiche: Klebolin klebt alles,DE,\N,alternative,\N,0
1,tt0000929,2,Klebolin klebt alles,\N,\N,original,\N,1
2,tt0000929,3,Klebolin klebt alles,DE,\N,imdbDisplay,\N,0
3,tt0000977,1,Mutterliebe,\N,\N,original,\N,1
4,tt0000977,2,Mutterliebe,DE,\N,imdbDisplay,\N,0
...,...,...,...,...,...,...,...,...
2802,tt0103054,1,Wer zweimal stirbt,DE,\N,\N,\N,0
2803,tt0103062,1,Tell Me That You Love Me,GB,\N,\N,\N,0
2804,tt0103071,1,Thanners neuer Job,DE,\N,\N,\N,0
2805,tt0103145,1,Two Teens and a Baby,US,\N,\N,\N,0
2806,tt0103149,1,Tödliche Vergangenheit,DE,\N,\N,\N,0

In [61]:
principals

         tconst  ordering     nconst         category       job characters
0     tt0000929         1  nm0066941            actor        \N         \N
1     tt0000929         2  nm0170183            actor        \N         \N
2     tt0000929         3  nm0092290            actor        \N         \N
3     tt0000929         4  nm0093361         director        \N         \N
4     tt0000929         5  nm1902148         producer  producer         \N
...         ...       ...        ...              ...       ...        ...
4474  tt0103149         5  nm0530689         director        \N         \N
4475  tt0103149         6  nm0773276         composer        \N         \N
4476  tt0103149         7  nm0049697  cinematographer        \N         \N
4477  tt0103149         8  nm0432619          actress        \N   ["Lilo"]
4478  tt0103149         9  nm0618291            actor        \N  ["Harry"]

[4479 rows x 6 columns]

In [ ]:
principals[principals['']]